In [1]:
import pandas as pd

In [131]:
df=pd.read_excel(r"C:\Users\acer\Downloads\Customer Call List.xlsx",index_col='CustomerID')
df

,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
CustomerID,,,,,,,
1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True
1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes,False
1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN,True
1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True
1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No,True
1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,True
1007,Jeff,Winger,NaN,1209 South Street,No,No,False
1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No,False
1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN,False
1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,True
1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No,True
1012,Harry,...Potter,7066950392,2394 Hogwarts Avenue,Y,NaN,True
1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False
1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No,False
1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No,False
1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False
1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No,False
1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN,True
1019,Creed,Braton,N/a,N/a,N/a,Yes,True
1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True
1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True

In [132]:
df=df.drop_duplicates()
df

,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
CustomerID,,,,,,,
1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True
1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes,False
1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN,True
1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True
1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No,True
1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,True
1007,Jeff,Winger,NaN,1209 South Street,No,No,False
1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No,False
1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN,False
1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,True
1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No,True
1012,Harry,...Potter,7066950392,2394 Hogwarts Avenue,Y,NaN,True
1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False
1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No,False
1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No,False
1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False
1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No,False
1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN,True
1019,Creed,Braton,N/a,N/a,N/a,Yes,True
1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True

In [133]:
df=df.drop(columns='Not_Useful_Column')
df

,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact
CustomerID,,,,,,
1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No
1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes
1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN
1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y
1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No
1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes
1007,Jeff,Winger,NaN,1209 South Street,No,No
1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No
1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN
1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No
1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No
1012,Harry,...Potter,7066950392,2394 Hogwarts Avenue,Y,NaN
1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N
1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No
1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No
1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N
1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No
1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN
1019,Creed,Braton,N/a,N/a,N/a,Yes
1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N

In [134]:
df['Last_Name']=df['Last_Name'].str.strip('123._/')
# df['Last_Name']=df['Last_Name'].str.lstrip('...')
# df['Last_Name']=df['Last_Name'].str.lstrip('/')
# df['Last_Name']=df['Last_Name'].str.lstrip('_')
df

,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact
CustomerID,,,,,,
1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No
1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes
1003,Walter,White,7066950392,298 Drugs Driveway,N,NaN
1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y
1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No
1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes
1007,Jeff,Winger,NaN,1209 South Street,No,No
1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No
1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN
1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No
1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No
1012,Harry,Potter,7066950392,2394 Hogwarts Avenue,Y,NaN
1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N
1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No
1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,No
1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N
1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No
1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN
1019,Creed,Braton,N/a,N/a,N/a,Yes
1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N

In [135]:
df['First_Name']=df['First_Name'].str.strip()
df

,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact
CustomerID,,,,,,
1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No
1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes
1003,Walter,White,7066950392,298 Drugs Driveway,N,NaN
1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y
1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No
1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes
1007,Jeff,Winger,NaN,1209 South Street,No,No
1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No
1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN
1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No
1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No
1012,Harry,Potter,7066950392,2394 Hogwarts Avenue,Y,NaN
1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N
1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No
1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,No
1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N
1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No
1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN
1019,Creed,Braton,N/a,N/a,N/a,Yes
1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N

In [136]:
df['Phone_Number']=df['Phone_Number'].str.replace('[^a-zA-Z0-9]','', regex=True)
df['Phone_Number']=df['Phone_Number'].apply(lambda x:str(x))
df['Phone_Number']=df['Phone_Number'].apply(lambda x: x[0:3]+'-'+ x[3:6]+'-' +x[6:10])
df['Phone_Number']=df['Phone_Number'].str.replace('nan--','')
df['Phone_Number']=df['Phone_Number'].str.replace('Na--','')
df

,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact
CustomerID,,,,,,
1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No
1002,Abed,Nadir,123-643-9775,93 West Main Street,No,Yes
1003,Walter,White,,298 Drugs Driveway,N,NaN
1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y
1005,Jon,Snow,876-678-3469,123 Dragons Road,Y,No
1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes
1007,Jeff,Winger,,1209 South Street,No,No
1008,Sherlock,Holmes,876-678-3469,98 Clue Drive,N,No
1009,Gandalf,NaN,,123 Middle Earth,Yes,NaN
1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No
1011,Samwise,Gamgee,,"612 Shire Lane, Shire",Yes,No
1012,Harry,Potter,,2394 Hogwarts Avenue,Y,NaN
1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N
1014,Leslie,Knope,876-678-3469,343 City Parkway,Yes,No
1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,No
1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N
1017,Michael,Scott,123-643-9775,"121 Paper Avenue, Pennsylvania",Yes,No
1018,Clark,Kent,,3498 Super Lane,Y,NaN
1019,Creed,Braton,,N/a,N/a,Yes
1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Yes,N

In [137]:
df[['Street_Address','State','Zip_cod']]=df['Address'].str.split(',',n=2,expand=True)
df

,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Street_Address,State,Zip_cod
CustomerID,,,,,,,,,
1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,123 Shire Lane,Shire,None
1002,Abed,Nadir,123-643-9775,93 West Main Street,No,Yes,93 West Main Street,None,None
1003,Walter,White,,298 Drugs Driveway,N,NaN,298 Drugs Driveway,None,None
1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,980 Paper Avenue,Pennsylvania,18503
1005,Jon,Snow,876-678-3469,123 Dragons Road,Y,No,123 Dragons Road,None,None
1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,768 City Parkway,None,None
1007,Jeff,Winger,,1209 South Street,No,No,1209 South Street,None,None
1008,Sherlock,Holmes,876-678-3469,98 Clue Drive,N,No,98 Clue Drive,None,None
1009,Gandalf,NaN,,123 Middle Earth,Yes,NaN,123 Middle Earth,None,None
1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,25th Main Street,New York,None
1011,Samwise,Gamgee,,"612 Shire Lane, Shire",Yes,No,612 Shire Lane,Shire,None
1012,Harry,Potter,,2394 Hogwarts Avenue,Y,NaN,2394 Hogwarts Avenue,None,None
1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,2039 Main Street,None,None
1014,Leslie,Knope,876-678-3469,343 City Parkway,Yes,No,343 City Parkway,None,None
1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,No,214 HR Avenue,None,None
1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,2395 Hogwarts Avenue,None,None
1017,Michael,Scott,123-643-9775,"121 Paper Avenue, Pennsylvania",Yes,No,121 Paper Avenue,Pennsylvania,None
1018,Clark,Kent,,3498 Super Lane,Y,NaN,3498 Super Lane,None,None
1019,Creed,Braton,,N/a,N/a,Yes,N/a,None,None
1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Yes,N,910 Tatooine Road,Tatooine,None

In [138]:
df['Paying Customer']=df['Paying Customer'].str.replace('No','N')
df['Paying Customer']=df['Paying Customer'].str.replace('Yes','Y')
df

,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Street_Address,State,Zip_cod
CustomerID,,,,,,,,,
1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Y,No,123 Shire Lane,Shire,None
1002,Abed,Nadir,123-643-9775,93 West Main Street,N,Yes,93 West Main Street,None,None
1003,Walter,White,,298 Drugs Driveway,N,NaN,298 Drugs Driveway,None,None
1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Y,Y,980 Paper Avenue,Pennsylvania,18503
1005,Jon,Snow,876-678-3469,123 Dragons Road,Y,No,123 Dragons Road,None,None
1006,Ron,Swanson,304-762-2467,768 City Parkway,Y,Yes,768 City Parkway,None,None
1007,Jeff,Winger,,1209 South Street,N,No,1209 South Street,None,None
1008,Sherlock,Holmes,876-678-3469,98 Clue Drive,N,No,98 Clue Drive,None,None
1009,Gandalf,NaN,,123 Middle Earth,Y,NaN,123 Middle Earth,None,None
1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Y,No,25th Main Street,New York,None
1011,Samwise,Gamgee,,"612 Shire Lane, Shire",Y,No,612 Shire Lane,Shire,None
1012,Harry,Potter,,2394 Hogwarts Avenue,Y,NaN,2394 Hogwarts Avenue,None,None
1013,Don,Draper,123-543-2345,2039 Main Street,Y,N,2039 Main Street,None,None
1014,Leslie,Knope,876-678-3469,343 City Parkway,Y,No,343 City Parkway,None,None
1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,No,214 HR Avenue,None,None
1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,N,N,2395 Hogwarts Avenue,None,None
1017,Michael,Scott,123-643-9775,"121 Paper Avenue, Pennsylvania",Y,No,121 Paper Avenue,Pennsylvania,None
1018,Clark,Kent,,3498 Super Lane,Y,NaN,3498 Super Lane,None,None
1019,Creed,Braton,,N/a,N/a,Yes,N/a,None,None
1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Y,N,910 Tatooine Road,Tatooine,None

In [139]:
df['Do_Not_Contact']=df['Do_Not_Contact'].str.replace('No','N')
df['Do_Not_Contact']=df['Do_Not_Contact'].str.replace('Yes','Y')
df

,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Street_Address,State,Zip_cod
CustomerID,,,,,,,,,
1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Y,N,123 Shire Lane,Shire,None
1002,Abed,Nadir,123-643-9775,93 West Main Street,N,Y,93 West Main Street,None,None
1003,Walter,White,,298 Drugs Driveway,N,NaN,298 Drugs Driveway,None,None
1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Y,Y,980 Paper Avenue,Pennsylvania,18503
1005,Jon,Snow,876-678-3469,123 Dragons Road,Y,N,123 Dragons Road,None,None
1006,Ron,Swanson,304-762-2467,768 City Parkway,Y,Y,768 City Parkway,None,None
1007,Jeff,Winger,,1209 South Street,N,N,1209 South Street,None,None
1008,Sherlock,Holmes,876-678-3469,98 Clue Drive,N,N,98 Clue Drive,None,None
1009,Gandalf,NaN,,123 Middle Earth,Y,NaN,123 Middle Earth,None,None
1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Y,N,25th Main Street,New York,None
1011,Samwise,Gamgee,,"612 Shire Lane, Shire",Y,N,612 Shire Lane,Shire,None
1012,Harry,Potter,,2394 Hogwarts Avenue,Y,NaN,2394 Hogwarts Avenue,None,None
1013,Don,Draper,123-543-2345,2039 Main Street,Y,N,2039 Main Street,None,None
1014,Leslie,Knope,876-678-3469,343 City Parkway,Y,N,343 City Parkway,None,None
1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,N,214 HR Avenue,None,None
1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,N,N,2395 Hogwarts Avenue,None,None
1017,Michael,Scott,123-643-9775,"121 Paper Avenue, Pennsylvania",Y,N,121 Paper Avenue,Pennsylvania,None
1018,Clark,Kent,,3498 Super Lane,Y,NaN,3498 Super Lane,None,None
1019,Creed,Braton,,N/a,N/a,Y,N/a,None,None
1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Y,N,910 Tatooine Road,Tatooine,None

In [140]:
df=df.replace('N/a','')
df=df.replace('Nne','')
df=df.fillna('')
df

,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Street_Address,State,Zip_cod
CustomerID,,,,,,,,,
1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Y,N,123 Shire Lane,Shire,
1002,Abed,Nadir,123-643-9775,93 West Main Street,N,Y,93 West Main Street,,
1003,Walter,White,,298 Drugs Driveway,N,,298 Drugs Driveway,,
1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Y,Y,980 Paper Avenue,Pennsylvania,18503
1005,Jon,Snow,876-678-3469,123 Dragons Road,Y,N,123 Dragons Road,,
1006,Ron,Swanson,304-762-2467,768 City Parkway,Y,Y,768 City Parkway,,
1007,Jeff,Winger,,1209 South Street,N,N,1209 South Street,,
1008,Sherlock,Holmes,876-678-3469,98 Clue Drive,N,N,98 Clue Drive,,
1009,Gandalf,,,123 Middle Earth,Y,,123 Middle Earth,,
1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Y,N,25th Main Street,New York,
1011,Samwise,Gamgee,,"612 Shire Lane, Shire",Y,N,612 Shire Lane,Shire,
1012,Harry,Potter,,2394 Hogwarts Avenue,Y,,2394 Hogwarts Avenue,,
1013,Don,Draper,123-543-2345,2039 Main Street,Y,N,2039 Main Street,,
1014,Leslie,Knope,876-678-3469,343 City Parkway,Y,N,343 City Parkway,,
1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,N,214 HR Avenue,,
1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,N,N,2395 Hogwarts Avenue,,
1017,Michael,Scott,123-643-9775,"121 Paper Avenue, Pennsylvania",Y,N,121 Paper Avenue,Pennsylvania,
1018,Clark,Kent,,3498 Super Lane,Y,,3498 Super Lane,,
1019,Creed,Braton,,,,Y,,,
1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Y,N,910 Tatooine Road,Tatooine,

In [141]:
df.reset_index()

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Street_Address,State,Zip_cod
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Y,N,123 Shire Lane,Shire,
1,1002,Abed,Nadir,123-643-9775,93 West Main Street,N,Y,93 West Main Street,,
2,1003,Walter,White,,298 Drugs Driveway,N,,298 Drugs Driveway,,
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Y,Y,980 Paper Avenue,Pennsylvania,18503
4,1005,Jon,Snow,876-678-3469,123 Dragons Road,Y,N,123 Dragons Road,,
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Y,Y,768 City Parkway,,
6,1007,Jeff,Winger,,1209 South Street,N,N,1209 South Street,,
7,1008,Sherlock,Holmes,876-678-3469,98 Clue Drive,N,N,98 Clue Drive,,
8,1009,Gandalf,,,123 Middle Earth,Y,,123 Middle Earth,,
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Y,N,25th Main Street,New York,
10,1011,Samwise,Gamgee,,"612 Shire Lane, Shire",Y,N,612 Shire Lane,Shire,
11,1012,Harry,Potter,,2394 Hogwarts Avenue,Y,,2394 Hogwarts Avenue,,
12,1013,Don,Draper,123-543-2345,2039 Main Street,Y,N,2039 Main Street,,
13,1014,Leslie,Knope,876-678-3469,343 City Parkway,Y,N,343 City Parkway,,
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,N,214 HR Avenue,,
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,N,N,2395 Hogwarts Avenue,,
16,1017,Michael,Scott,123-643-9775,"121 Paper Avenue, Pennsylvania",Y,N,121 Paper Avenue,Pennsylvania,
17,1018,Clark,Kent,,3498 Super Lane,Y,,3498 Super Lane,,
18,1019,Creed,Braton,,,,Y,,,
19,1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Y,N,910 Tatooine Road,Tatooine,

In [142]:
for x in df.index:
    if df.loc[x,'Do_Not_Contact']=='Y':
        df.drop(x,inplace=True)
df

,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Street_Address,State,Zip_cod
CustomerID,,,,,,,,,
1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Y,N,123 Shire Lane,Shire,
1003,Walter,White,,298 Drugs Driveway,N,,298 Drugs Driveway,,
1005,Jon,Snow,876-678-3469,123 Dragons Road,Y,N,123 Dragons Road,,
1007,Jeff,Winger,,1209 South Street,N,N,1209 South Street,,
1008,Sherlock,Holmes,876-678-3469,98 Clue Drive,N,N,98 Clue Drive,,
1009,Gandalf,,,123 Middle Earth,Y,,123 Middle Earth,,
1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Y,N,25th Main Street,New York,
1011,Samwise,Gamgee,,"612 Shire Lane, Shire",Y,N,612 Shire Lane,Shire,
1012,Harry,Potter,,2394 Hogwarts Avenue,Y,,2394 Hogwarts Avenue,,
1013,Don,Draper,123-543-2345,2039 Main Street,Y,N,2039 Main Street,,
1014,Leslie,Knope,876-678-3469,343 City Parkway,Y,N,343 City Parkway,,
1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,N,214 HR Avenue,,
1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,N,N,2395 Hogwarts Avenue,,
1017,Michael,Scott,123-643-9775,"121 Paper Avenue, Pennsylvania",Y,N,121 Paper Avenue,Pennsylvania,
1018,Clark,Kent,,3498 Super Lane,Y,,3498 Super Lane,,
1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Y,N,910 Tatooine Road,Tatooine,

In [143]:
for x in df.index:
    if df.loc[x,'Phone_Number']=='':
        df.drop(x,inplace=True)
df

,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Street_Address,State,Zip_cod
CustomerID,,,,,,,,,
1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Y,N,123 Shire Lane,Shire,
1005,Jon,Snow,876-678-3469,123 Dragons Road,Y,N,123 Dragons Road,,
1008,Sherlock,Holmes,876-678-3469,98 Clue Drive,N,N,98 Clue Drive,,
1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Y,N,25th Main Street,New York,
1013,Don,Draper,123-543-2345,2039 Main Street,Y,N,2039 Main Street,,
1014,Leslie,Knope,876-678-3469,343 City Parkway,Y,N,343 City Parkway,,
1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,N,214 HR Avenue,,
1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,N,N,2395 Hogwarts Avenue,,
1017,Michael,Scott,123-643-9775,"121 Paper Avenue, Pennsylvania",Y,N,121 Paper Avenue,Pennsylvania,
1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Y,N,910 Tatooine Road,Tatooine,

In [147]:
df=df.reset_index()
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Street_Address,State,Zip_cod
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Y,N,123 Shire Lane,Shire,
1,1005,Jon,Snow,876-678-3469,123 Dragons Road,Y,N,123 Dragons Road,,
2,1008,Sherlock,Holmes,876-678-3469,98 Clue Drive,N,N,98 Clue Drive,,
3,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Y,N,25th Main Street,New York,
4,1013,Don,Draper,123-543-2345,2039 Main Street,Y,N,2039 Main Street,,
5,1014,Leslie,Knope,876-678-3469,343 City Parkway,Y,N,343 City Parkway,,
6,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,N,214 HR Avenue,,
7,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,N,N,2395 Hogwarts Avenue,,
8,1017,Michael,Scott,123-643-9775,"121 Paper Avenue, Pennsylvania",Y,N,121 Paper Avenue,Pennsylvania,
9,1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Y,N,910 Tatooine Road,Tatooine,